branch-defaults:
  master:
    environment: budgetai-env
environment-defaults:
  budgetai-env:
    branch: null
    repository: null
global:
  application_name: budgetai
  default_ec2_keyname: null
  default_platform: Docker
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
option_settings:
  aws:autoscaling:asg:
    MaxSize: 2
    MinSize: 1
  aws:autoscaling:launchtemplate:
    DisableIMDSv1: true
  aws:ec2:instances:
    InstanceTypes: t3.micro
  aws:elasticbeanstalk:application:environment:
    ADMIN_EMAIL: ${ADMIN_EMAIL}
    AWS_ACCESS: ${AWS_ACCESS}
    AWS_SECRET: ${AWS_SECRET}
    ENVIRONMENT: production
    JWT_AUDIENCE: ${JWT_AUDIENCE}
    JWT_ISSUER: ${JWT_ISSUER}
    JWT_REALM: ${JWT_REALM}
    JWT_SECRET: ${JWT_SECRET}
    OPEN_AI: ${OPEN_AI}
    PORT: 8080
  aws:elasticbeanstalk:cloudwatch:logs:
    DeleteOnTerminate: false
    StreamLogs: true
  aws:elasticbeanstalk:container:docker:
    PORT: 8080
