branch-defaults:
  master:
    environment: budgetai-env
global:
  application_name: budgetai
  default_platform: Docker
  default_region: eu-west-1
  sc: git
  workspace_type: Application
option_settings:
  aws:elasticbeanstalk:application:environment:
    ADMIN_EMAIL: ${ADMIN_EMAIL}
    AWS_ACCESS: ${AWS_ACCESS}
    AWS_SECRET: ${AWS_SECRET}
    ENVIRONMENT: production
    JWT_AUDIENCE: ${JWT_AUDIENCE}
    JWT_ISSUER: ${JWT_ISSUER}
    JWT_REALM: ${JWT_REALM}
    JWT_SECRET: ${JWT_SECRET}
    OPEN_AI: ${OPEN_AI}
    PORT: 8080