branch-defaults:
  main:
    environment: budgetai-env
environment-defaults:
  your-app-name-env:
    branch: null
    repository: null
global:
  application_name: budgetai
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application