branch-defaults:
  master:
    environment: budgetai-env
global:
  application_name: budgetai
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  workspace_type: Application

option_settings:
  aws:elasticbeanstalk:application:environment:
    PORT: 8080
    ENVIRONMENT: production
    OPEN_AI: ${OPEN_AI}
    AWS_ACCESS: ${AWS_ACCESS}
    AWS_SECRET: ${AWS_SECRET}
    JWT_AUDIENCE: ${JWT_AUDIENCE}
    JWT_ISSUER: ${JWT_ISSUER}
    JWT_REALM: ${JWT_REALM}
    JWT_SECRET: ${JWT_SECRET}
    ADMIN_EMAIL: ${ADMIN_EMAIL}