name: Gradle Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Adjust this to your project's Java version
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      # Optional: Publish test report when tests fail
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'