name: Gradle Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  KTOR_ENV: development
  PORT: 8080

jobs:
  test:
    name: Run Gradle Tests
    runs-on: ubuntu-latest

    env:
      JDBC_DATABASE_URL: jdbc:sqlite:file:test?mode=memory&cache=shared

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        env:
          OPEN_AI: ${{ secrets.OPEN_AI }}
          AWS_ACCESS: ${{ secrets.AWS_ACCESS }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_REALM: ${{ secrets.JWT_REALM }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}

        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'